services:

  frontend:
    build: ./Frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    container_name: node_backend
    ports:
      - "5000:5000"

  ai-pipeline:
    build: ./AI_pipeline
    container_name: ai_pipeline
    ports:
      - "8000:8000"